### ISSUE TITLE
 is there another kind of codes just like matlab or C++? 

### ISSUE THREAD

**Issue by TiantianZhang** [mborgerding/onsager_deep_learning#1]
This is a very cool job!! But the python is not so easy to understand

**Comment by mborgerding** [comment]
In the next couple of weeks.  I will be revising this project to add new material in support for an upcoming publication.  The goals are to improve the organization, make the code easier to follow, and make it easier for researchers to replicate the paper results.  It is _not_ a goal to move away from the Python code.  Python is the most mature language binding for TensorFlow as well as other deep learning toolkits.  If you'd like to offer your help in this effort, let me know.

**Comment by TiantianZhang** [comment]
Thanks for you replay. I learned Python several weeks ago and can write some simple project by myself. That is really a cool tools to do some calculation and the deep learning API. So, I'm glad to do something in your project if there is something to deal with. Thanks !!!

**Comment by mborgerding** [comment]
I've changed quite a bit.  I hope it should be much easier to follow along and replicate the paper.
