### ISSUE TITLE
wrong results

### ISSUE THREAD

**Issue by fahimehansari** [mborgerding/onsager_deep_learning#2]
Hi Mark, Very thanks for your work.  I implemented your code but my results for LVAMP are completely different. however, I didn't change your code at all. I just specified shrinkage function and numbers of layers! I reproduced all traces that are in figures of your paper.  for example, I reproduced "fig12" up to 10 layers and its result was as below:
![image](https://user-images.githubusercontent.com/33966658/33228276-6366ea00-d1cc-11e7-9dcb-c868dced6fae.png)
and for "LVAMP-pwlin" at T=4, it errored!  based my results, the performance of LVAMP is worse than LISTA and LAMP. also for MIMO problem, when I run LAMP and LVAMP at T=3(third layer) it errors that nmse is nan! 
 have you changed the codes which are on the GitHub?

**Comment by mborgerding** [comment]
Can you give me a little more information about the system that you're trying to use this? OS? GPU? versions? Have other Tensorflow apps worked?

**Comment by fahimehansari** [comment]
linux 16.0.4 LTS, GPU 1070
its results for LISTA and LAMP are almost matched.

**Comment by mborgerding** [comment]
So your graph does not show results from the first 2 layers.  Are those outside of your current axis bounds?

Are your results getting corrupted by a bad .npz file from a previous run with different parameters?  i.e. did you try to rename/remove the .npz file referenced in the "do_training" call?

I made a small _testing_ branch to try to help you reproduce the results.
The LVAMP.py script will currently reproduce the first 2 layers of the _lvamp-bg_ trace of Fig 12 (kappa=100).
If you run `./LVAMP.py` from this branch, you should see it start something like

> Creating the basic problem structure
> building the LVAMP network in tensorflow
> theta_init=(1, 2.1972245773362196)
> svd reconstruction error=-129.949dB
> setup_training
> do_training
> norms xval:224.5516510 yval:224.5218856
> LVAMP-bg T=1 trainrate=0.5 fine tuning all logyvar:0,theta_0:0,theta_1:0
> i=0      nmse=-0.402147 dB (best=-0.402147)
> i=1000   nmse=-0.451789 dB (best=-0.451789)
> i=2000   nmse=-0.506670 dB (best=-0.506670)
> i=3000   nmse=-0.566217 dB (best=-0.566217)
> i=4000   nmse=-0.629872 dB (best=-0.629872)
> i=5000   nmse=-0.696972 dB (best=-0.696972)
> i=6000   nmse=-0.766951 dB (best=-0.766951)
> i=7000   nmse=-0.839125 dB (best=-0.839125)
> i=8000   nmse=-0.912848 dB (best=-0.912848)
> i=9000   nmse=-0.987421 dB (best=-0.987421)
> i=10000  nmse=-1.062157 dB (best=-1.062157)
> i=11000  nmse=-1.136317 dB (best=-1.136317)
> i=12000  nmse=-1.209268 dB (best=-1.209268)
> i=13000  nmse=-1.280282 dB (best=-1.280282)
> i=14000  nmse=-1.348699 dB (best=-1.348699)
> i=15000  nmse=-1.414037 dB (best=-1.414037)
> i=16000  nmse=-1.475692 dB (best=-1.475692)
> i=17000  nmse=-1.533344 dB (best=-1.533344)
> i=18000  nmse=-1.586709 dB (best=-1.586709)
> i=19000  nmse=-1.635595 dB (best=-1.635595)
> i=20000  nmse=-1.680285 dB (best=-1.680285)

Then when it completes, you should be able to run
`./dump_npz.py LVAMP_bg_k100.npz`

> Loading LVAMP_bg_k100.npz
> done:['LVAMP-bg T=1 trainrate=0.5' 'LVAMP-bg T=1 trainrate=0.1'
>  'LVAMP-bg T=1 trainrate=0.01' 'LVAMP-bg T=2' 'LVAMP-bg T=2 trainrate=0.5'
>  'LVAMP-bg T=2 trainrate=0.1' 'LVAMP-bg T=2 trainrate=0.01']
> log:
> LVAMP-bg T=1 trainrate=0.5 nmse=-6.595706 dB in 229000 iterations
> LVAMP-bg T=1 trainrate=0.1 nmse=-6.595698 dB in 6000 iterations
> LVAMP-bg T=1 trainrate=0.01 nmse=-6.595698 dB in 6000 iterations
> LVAMP-bg T=2 nmse=-12.019060 dB in 6000 iterations
> LVAMP-bg T=2 trainrate=0.5 nmse=-12.030993 dB in 31000 iterations
> LVAMP-bg T=2 trainrate=0.1 nmse=-12.030989 dB in 7000 iterations
> LVAMP-bg T=2 trainrate=0.01 nmse=-12.030990 dB in 11000 iterations
> logyvar:0:-10.7385969162
> theta_0:0:[ 1.05167186  2.158427  ]
> theta_1:0:[ 0.92155612  2.28668165]
>

**Comment by mborgerding** [comment]
By changing `shrink='pwlin'` and naming a different file in `do_training`
I reproduce the lvamp-pwlin trace from Fig 12.

The _log_ item in the .npz file is

> LVAMP-pwlin T=1 trainrate=0.5 nmse=-6.560794 dB in 228000 iterations
> LVAMP-pwlin T=1 trainrate=0.1 nmse=-6.560887 dB in 12000 iterations
> LVAMP-pwlin T=1 trainrate=0.01 nmse=-6.560869 dB in 6000 iterations
> LVAMP-pwlin T=2 nmse=-11.946056 dB in 26000 iterations
> LVAMP-pwlin T=2 trainrate=0.5 nmse=-11.950997 dB in 10000 iterations
> LVAMP-pwlin T=2 trainrate=0.1 nmse=-11.951137 dB in 7000 iterations
> LVAMP-pwlin T=2 trainrate=0.01 nmse=-11.951190 dB in 16000 iterations
> LVAMP-pwlin T=3 nmse=-17.350595 dB in 29000 iterations
> LVAMP-pwlin T=3 trainrate=0.5 nmse=-17.363667 dB in 28000 iterations
> LVAMP-pwlin T=3 trainrate=0.1 nmse=-17.363765 dB in 10000 iterations
> LVAMP-pwlin T=3 trainrate=0.01 nmse=-17.363977 dB in 20000 iterations
> LVAMP-pwlin T=4 nmse=-22.583890 dB in 57000 iterations
> LVAMP-pwlin T=4 trainrate=0.5 nmse=-22.588935 dB in 34000 iterations
> LVAMP-pwlin T=4 trainrate=0.1 nmse=-22.589233 dB in 12000 iterations
> LVAMP-pwlin T=4 trainrate=0.01 nmse=-22.589903 dB in 10000 iterations
> LVAMP-pwlin T=5 nmse=-27.283349 dB in 21000 iterations
> LVAMP-pwlin T=5 trainrate=0.5 nmse=-27.282407 dB in 18000 iterations
> LVAMP-pwlin T=5 trainrate=0.1 nmse=-27.283647 dB in 19000 iterations
> LVAMP-pwlin T=5 trainrate=0.01 nmse=-27.284381 dB in 17000 iterations
> LVAMP-pwlin T=6 nmse=-31.235235 dB in 24000 iterations
> LVAMP-pwlin T=6 trainrate=0.5 nmse=-31.223166 dB in 6000 iterations
> LVAMP-pwlin T=6 trainrate=0.1 nmse=-31.223857 dB in 8000 iterations
> LVAMP-pwlin T=6 trainrate=0.01 nmse=-31.224022 dB in 14000 iterations

**Comment by mborgerding** [comment]
I'm also seeing the NaNs with LVAMP+pwgrid on the Massive MIMO problem when it gets to the non-linear stage of layer 3.
I think there might have been something lost when I refactored the code.

It appears `alpha_nl_` in `tools.build_LVAMP_dense` was negative.  It should be restricted to (0,1). Clipping it, as was done with `alpha_lin_`, allows the script to get past the trouble spot.

I am rerunning the trial from the beginning to verify it does reproduce the LVAMP_pwlin  trace from Fig 16.  Once verified, I will push this to the `testing` branch and cherry-pick the clipping commit it to the master branch.

**Comment by fahimehansari** [comment]
thanks a lot for your answering. I rerun the LVAMP.py and renamed the .npz file referenced in the "do_training" call. If I run ./LVAMP.py for 2 first layers of the lvamp-bg trace of Fig 12 (kappa=100) , I see it start something like

```
theta_init=(1, 2.1972245773362196)
svd reconstruction error=-132.542dB
norms xval:224.5517120 yval:224.5218854
LVAMP-bg T=1 trainrate=0.5 fine tuning all logyvar:0,theta_0:0,theta_1:0
i=0      nmse=-0.402148 dB (best=-0.402148)
i=1000   nmse=-0.451788 dB (best=-0.451788)
i=2000   nmse=-0.506670 dB (best=-0.506670)
i=3000   nmse=-0.566215 dB (best=-0.566215)
i=4000   nmse=-0.629871 dB (best=-0.629871)
i=5000   nmse=-0.696971 dB (best=-0.696971)
i=6000   nmse=-0.766951 dB (best=-0.766951)
i=7000   nmse=-0.839124 dB (best=-0.839124)
i=8000   nmse=-0.912847 dB (best=-0.912847)
i=9000   nmse=-0.987419 dB (best=-0.987419)
i=10000  nmse=-1.062157 dB (best=-1.062157)
LVAMP-bg T=1 trainrate=0.1 fine tuning all logyvar:0,theta_0:0,theta_1:0
i=0      nmse=-1.062228 dB (best=-1.062228)
i=1000   nmse=-1.077227 dB (best=-1.077227)
i=2000   nmse=-1.092205 dB (best=-1.092205)
i=3000   nmse=-1.107149 dB (best=-1.107149)
i=4000   nmse=-1.122058 dB (best=-1.122058)
i=5000   nmse=-1.136951 dB (best=-1.136951)
i=6000   nmse=-1.151808 dB (best=-1.151808)
i=7000   nmse=-1.166635 dB (best=-1.166635)
i=8000   nmse=-1.181421 dB (best=-1.181421)
i=9000   nmse=-1.196150 dB (best=-1.196150)
i=10000  nmse=-1.210833 dB (best=-1.210833)
LVAMP-bg T=1 trainrate=0.01 fine tuning all logyvar:0,theta_0:0,theta_1:0
i=0      nmse=-1.210847 dB (best=-1.210847)
i=1000   nmse=-1.212295 dB (best=-1.212295)
i=2000   nmse=-1.213744 dB (best=-1.213744)
i=3000   nmse=-1.215194 dB (best=-1.215194)
i=4000   nmse=-1.216641 dB (best=-1.216641)
i=5000   nmse=-1.218087 dB (best=-1.218087)
i=6000   nmse=-1.219535 dB (best=-1.219535)
i=7000   nmse=-1.220979 dB (best=-1.220979)
i=8000   nmse=-1.222425 dB (best=-1.222425)
i=9000   nmse=-1.223871 dB (best=-1.223871)
i=10000  nmse=-1.225314 dB (best=-1.225314)
LVAMP-bg T=2 extending theta_1:0
i=0      nmse=-0.557441 dB (best=-0.557441)
i=1000   nmse=-0.767010 dB (best=-0.767010)
i=2000   nmse=-1.038713 dB (best=-1.038713)
i=3000   nmse=-1.335831 dB (best=-1.335831)
i=4000   nmse=-1.602646 dB (best=-1.602646)
i=5000   nmse=-1.800293 dB (best=-1.800293)
i=6000   nmse=-1.942879 dB (best=-1.942879)
i=7000   nmse=-2.079257 dB (best=-2.079257)
i=8000   nmse=-2.222581 dB (best=-2.222581)
i=9000   nmse=-2.370510 dB (best=-2.370510)
i=10000  nmse=-2.520937 dB (best=-2.520937)
LVAMP-bg T=2 trainrate=0.5 fine tuning all logyvar:0,theta_0:0,theta_1:0
i=0      nmse=-2.521087 dB (best=-2.521087)
i=1000   nmse=-2.599251 dB (best=-2.599251)
i=2000   nmse=-2.676306 dB (best=-2.676306)
i=3000   nmse=-2.752643 dB (best=-2.752643)
i=4000   nmse=-2.828240 dB (best=-2.828240)
i=5000   nmse=-2.903252 dB (best=-2.903252)
i=6000   nmse=-2.977561 dB (best=-2.977561)
i=7000   nmse=-3.051152 dB (best=-3.051152)
i=8000   nmse=-3.123983 dB (best=-3.123983)
i=9000   nmse=-3.196091 dB (best=-3.196091)
i=10000  nmse=-3.267367 dB (best=-3.267367)
LVAMP-bg T=2 trainrate=0.1 fine tuning all logyvar:0,theta_0:0,theta_1:0
i=0      nmse=-3.267440 dB (best=-3.267440)
i=1000   nmse=-3.281953 dB (best=-3.281953)
i=2000   nmse=-3.296414 dB (best=-3.296414)
i=3000   nmse=-3.310825 dB (best=-3.310824)
i=4000   nmse=-3.325188 dB (best=-3.325188)
i=5000   nmse=-3.339505 dB (best=-3.339505)
i=6000   nmse=-3.353786 dB (best=-3.353786)
i=7000   nmse=-3.368029 dB (best=-3.368029)
i=8000   nmse=-3.382215 dB (best=-3.382216)
i=9000   nmse=-3.396363 dB (best=-3.396363)
i=10000  nmse=-3.410471 dB (best=-3.410471)
LVAMP-bg T=2 trainrate=0.01 fine tuning all logyvar:0,theta_0:0,theta_1:0
i=0      nmse=-3.410486 dB (best=-3.410486)
i=1000   nmse=-3.411834 dB (best=-3.411834)
i=2000   nmse=-3.413180 dB (best=-3.413180)
i=3000   nmse=-3.414525 dB (best=-3.414525)
i=4000   nmse=-3.415870 dB (best=-3.415870)
i=5000   nmse=-3.417215 dB (best=-3.417215)
i=6000   nmse=-3.418560 dB (best=-3.418560)
i=7000   nmse=-3.419903 dB (best=-3.419903)
i=8000   nmse=-3.421246 dB (best=-3.421246)
i=9000   nmse=-3.422586 dB (best=-3.422586)
i=10000  nmse=-3.423932 dB (best=-3.423932)

Process finished with exit code 0

```
and when it completes, The log item in the .npz file is

```
LVAMP-bg T=1 trainrate=0.5 nmse=-1.062157 dB in 10000 iterations
LVAMP-bg T=1 trainrate=0.1 nmse=-1.210833 dB in 10000 iterations
LVAMP-bg T=1 trainrate=0.01 nmse=-1.225314 dB in 10000 iterations
LVAMP-bg T=2 nmse=-2.520937 dB in 10000 iterations
LVAMP-bg T=2 trainrate=0.5 nmse=-3.267367 dB in 10000 iterations
LVAMP-bg T=2 trainrate=0.1 nmse=-3.410471 dB in 10000 iterations
LVAMP-bg T=2 trainrate=0.01 nmse=-3.423932 dB in 10000 iterations
```

**Comment by fahimehansari** [comment]
I also rename and rerun lvamp_pwlin. but it errors again:
```
theta_init=(2, 4, 0.1, 1.5, 0.95)
svd reconstruction error=-132.542dB
setup training
do training
norms xval:224.5517120 yval:224.5218854
LVAMP-pwlin T=1 trainrate=0.5 fine tuning all logyvar:0,theta_0:0,theta_1:0,theta_2:0,theta_3:0,theta_4:0,theta_5:0,theta_6:0,theta_7:0,theta_8:0,theta_9:0
i=0      nmse=-0.919051 dB (best=-0.919051)
i=1000   nmse=-1.020652 dB (best=-1.020652)
i=2000   nmse=-1.082885 dB (best=-1.082885)
i=3000   nmse=-1.145740 dB (best=-1.145740)
i=4000   nmse=-1.205552 dB (best=-1.205552)
i=5000   nmse=-1.260834 dB (best=-1.260834)
i=6000   nmse=-1.316113 dB (best=-1.316113)
i=7000   nmse=-1.371388 dB (best=-1.371387)
i=8000   nmse=-1.423024 dB (best=-1.423024)
i=9000   nmse=-1.470990 dB (best=-1.470990)
i=10000  nmse=-1.515696 dB (best=-1.515696)
LVAMP-pwlin T=1 trainrate=0.1 fine tuning all logyvar:0,theta_0:0,theta_1:0,theta_2:0,theta_3:0,theta_4:0,theta_5:0,theta_6:0,theta_7:0,theta_8:0,theta_9:0
i=0      nmse=-1.515738 dB (best=-1.515738)
i=1000   nmse=-1.524854 dB (best=-1.524854)
i=2000   nmse=-1.533833 dB (best=-1.533833)
i=3000   nmse=-1.542581 dB (best=-1.542581)
i=4000   nmse=-1.551060 dB (best=-1.551060)
i=5000   nmse=-1.559206 dB (best=-1.559206)
i=6000   nmse=-1.567064 dB (best=-1.567064)
i=7000   nmse=-1.574730 dB (best=-1.574730)
i=8000   nmse=-1.582178 dB (best=-1.582178)
i=9000   nmse=-1.589541 dB (best=-1.589541)
i=10000  nmse=-1.596782 dB (best=-1.596782)
LVAMP-pwlin T=1 trainrate=0.01 fine tuning all logyvar:0,theta_0:0,theta_1:0,theta_2:0,theta_3:0,theta_4:0,theta_5:0,theta_6:0,theta_7:0,theta_8:0,theta_9:0
i=0      nmse=-1.596788 dB (best=-1.596788)
i=1000   nmse=-1.597530 dB (best=-1.597530)
i=2000   nmse=-1.598269 dB (best=-1.598269)
i=3000   nmse=-1.599004 dB (best=-1.599004)
i=4000   nmse=-1.599738 dB (best=-1.599738)
i=5000   nmse=-1.600465 dB (best=-1.600465)
i=6000   nmse=-1.601192 dB (best=-1.601192)
i=7000   nmse=-1.601909 dB (best=-1.601909)
i=8000   nmse=-1.602625 dB (best=-1.602625)
i=9000   nmse=-1.603336 dB (best=-1.603336)
i=10000  nmse=-1.604047 dB (best=-1.604046)
LVAMP-pwlin T=2 extending theta_1:0
i=0      nmse=-1.019171 dB (best=-1.019171)
i=1000   nmse=-1.705392 dB (best=-1.705392)
i=2000   nmse=-1.867449 dB (best=-1.867449)
i=3000   nmse=-2.036419 dB (best=-2.036419)
i=4000   nmse=-2.216016 dB (best=-2.216016)
i=5000   nmse=-2.407912 dB (best=-2.407912)
i=6000   nmse=-2.611218 dB (best=-2.611218)
i=7000   nmse=-2.827407 dB (best=-2.827407)
i=8000   nmse=-3.053885 dB (best=-3.053885)
i=9000   nmse=-3.293323 dB (best=-3.293323)
i=10000  nmse=-3.550889 dB (best=-3.550889)
LVAMP-pwlin T=2 trainrate=0.5 fine tuning all logyvar:0,theta_0:0,theta_1:0,theta_2:0,theta_3:0,theta_4:0,theta_5:0,theta_6:0,theta_7:0,theta_8:0,theta_9:0
i=0      nmse=-3.551171 dB (best=-3.551171)
i=1000   nmse=-3.686559 dB (best=-3.686559)
i=2000   nmse=-3.826554 dB (best=-3.826554)
i=3000   nmse=-3.972446 dB (best=-3.972446)
i=4000   nmse=-4.124269 dB (best=-4.124269)
i=5000   nmse=-4.286789 dB (best=-4.286789)
i=6000   nmse=-4.454246 dB (best=-4.454246)
i=7000   nmse=-4.629067 dB (best=-4.629067)
i=8000   nmse=-4.814193 dB (best=-4.814193)
i=9000   nmse=-5.011747 dB (best=-5.011747)
i=10000  nmse=-5.221391 dB (best=-5.221391)
LVAMP-pwlin T=2 trainrate=0.1 fine tuning all logyvar:0,theta_0:0,theta_1:0,theta_2:0,theta_3:0,theta_4:0,theta_5:0,theta_6:0,theta_7:0,theta_8:0,theta_9:0
i=0      nmse=-5.221654 dB (best=-5.221654)
i=1000   nmse=-5.264102 dB (best=-5.264101)
i=2000   nmse=-5.308673 dB (best=-5.308673)
i=3000   nmse=-5.353590 dB (best=-5.353590)
i=4000   nmse=-5.397881 dB (best=-5.397881)
i=5000   nmse=-5.443400 dB (best=-5.443400)
i=6000   nmse=-5.491318 dB (best=-5.491318)
i=7000   nmse=-5.538749 dB (best=-5.538748)
i=8000   nmse=-5.586755 dB (best=-5.586755)
i=9000   nmse=-5.635372 dB (best=-5.635373)
i=10000  nmse=-5.685079 dB (best=-5.685079)
LVAMP-pwlin T=2 trainrate=0.01 fine tuning all logyvar:0,theta_0:0,theta_1:0,theta_2:0,theta_3:0,theta_4:0,theta_5:0,theta_6:0,theta_7:0,theta_8:0,theta_9:0
i=0      nmse=-5.685135 dB (best=-5.685134)
i=1000   nmse=-5.690228 dB (best=-5.690228)
i=2000   nmse=-5.695328 dB (best=-5.695327)
i=3000   nmse=-5.700358 dB (best=-5.700358)
i=4000   nmse=-5.705345 dB (best=-5.705344)
i=5000   nmse=-5.710303 dB (best=-5.710303)
i=6000   nmse=-5.715237 dB (best=-5.715237)
i=7000   nmse=-5.720187 dB (best=-5.720187)
i=8000   nmse=-5.725135 dB (best=-5.725135)
i=9000   nmse=-5.730065 dB (best=-5.730064)
i=10000  nmse=-5.735226 dB (best=-5.735225)
LVAMP-pwlin T=3 extending theta_2:0
i=0      nmse=-0.902505 dB (best=-0.902505)
i=850    nmse=-2.991134 dB (best=-2.991134)Traceback (most recent call last):
  File "/home/khademi/ansari/onsager_deep_learning-master/LVAMP.py", line 37, in <module>
    sess = train.do_training(training_stages,prob,'LVAMP_pwlin_T2_K100_rerun.npz')
  File "/home/khademi/ansari/onsager_deep_learning-master/tools/train.py", line 109, in do_training
    raise RuntimeError('nmse is NaN')
RuntimeError: nmse is NaN

Process finished with exit code 1
```

**Comment by fahimehansari** [comment]
By the way, I have another question:
why do you have 3 trainrate (0.5,0.1,0.01)?

**Comment by mborgerding** [comment]
It looks like our results are the same until i=10000, at which point your script stops training even though the NMSE is improving.  Can you double check that you have not set `maxit` too low?

**Comment by mborgerding** [comment]
The multiple train rates are multipliers that get applied the base training rate to progressively reduce the step size.

**Comment by mborgerding** [comment]
I pushed some commits to the `testing` branch that set up LVAMP.py to reproduce the LVAMP-pwlin trace from Fig 16 (Massive MIMO).  It is the same as the paper trace up to 4 layers (still running).

`./dump_npz.py LVAMP_mmimo.npz`
> ...
> log:
> Linear trainrate=0.5 nmse=-4.695839 dB in 19000 iterations
> Linear trainrate=0.1 nmse=-4.698839 dB in 23000 iterations
> Linear trainrate=0.01 nmse=-4.698968 dB in 15000 iterations
> LVAMP-pwgrid T=1 trainrate=0.5 nmse=-8.719739 dB in 26000 iterations
> LVAMP-pwgrid T=1 trainrate=0.1 nmse=-8.720886 dB in 17000 iterations
> LVAMP-pwgrid T=1 trainrate=0.01 nmse=-8.721101 dB in 17000 iterations
> LVAMP-pwgrid lin T=2 nmse=-10.036980 dB in 16000 iterations
> LVAMP-pwgrid lin T=2 trainrate=0.5 nmse=-10.067803 dB in 37000 iterations
> LVAMP-pwgrid lin T=2 trainrate=0.1 nmse=-10.074787 dB in 19000 iterations
> LVAMP-pwgrid lin T=2 trainrate=0.01 nmse=-10.075719 dB in 19000 iterations
> LVAMP-pwgrid  nl T=2 nmse=-10.502646 dB in 20000 iterations
> LVAMP-pwgrid  nl T=2 trainrate=0.5 nmse=-11.317642 dB in 26000 iterations
> LVAMP-pwgrid  nl T=2 trainrate=0.1 nmse=-11.326778 dB in 23000 iterations
> LVAMP-pwgrid  nl T=2 trainrate=0.01 nmse=-11.329303 dB in 13000 iterations
> LVAMP-pwgrid lin T=3 nmse=-11.600415 dB in 18000 iterations
> LVAMP-pwgrid lin T=3 trainrate=0.5 nmse=-11.957065 dB in 66000 iterations
> LVAMP-pwgrid lin T=3 trainrate=0.1 nmse=-11.979263 dB in 15000 iterations
> LVAMP-pwgrid lin T=3 trainrate=0.01 nmse=-11.985062 dB in 23000 iterations
> LVAMP-pwgrid  nl T=3 nmse=-12.104664 dB in 242000 iterations
> LVAMP-pwgrid  nl T=3 trainrate=0.5 nmse=-12.033529 dB in 6000 iterations
> LVAMP-pwgrid  nl T=3 trainrate=0.1 nmse=-12.271782 dB in 80000 iterations
> LVAMP-pwgrid  nl T=3 trainrate=0.01 nmse=-12.282580 dB in 30000 iterations
> LVAMP-pwgrid lin T=4 nmse=-12.397929 dB in 30000 iterations
> LVAMP-pwgrid lin T=4 trainrate=0.5 nmse=-12.796084 dB in 75000 iterations
> LVAMP-pwgrid lin T=4 trainrate=0.1 nmse=-12.845693 dB in 17000 iterations
> LVAMP-pwgrid lin T=4 trainrate=0.01 nmse=-12.854502 dB in 21000 iterations
> LVAMP-pwgrid  nl T=4 nmse=-7.694938 dB in 20000 iterations
> LVAMP-pwgrid  nl T=4 trainrate=0.5 nmse=-12.954947 dB in 102000 iterations
> LVAMP-pwgrid  nl T=4 trainrate=0.1 nmse=-13.010908 dB in 19000 iterations
> LVAMP-pwgrid  nl T=4 trainrate=0.01 nmse=-13.019216 dB in 28000 iterations
>

**Comment by mborgerding** [comment]
FYI, I also cherry-picked the divergence clipping commit onto the master branch c94ea234c7e1ac0fe9b7b3f9bc6847f406d20c4e
.  This allows  `LVAMP_dense`+`pwgrid` to reproduce 'LVAMP-pwlin' from Fig 16.

**Comment by mborgerding** [comment]
Just an update ...  the script with LVAMP+piecewise and the massive MIMO problem finished as expected.

> $ ./dump_npz.py LVAMP_mmimo.npz | grep 'LVAMP-pwgrid  nl T=. trainrate=0.01 nmse='
> LVAMP-pwgrid  nl T=2 trainrate=0.01 nmse=-11.329303 dB in 13000 iterations
> LVAMP-pwgrid  nl T=3 trainrate=0.01 nmse=-12.282580 dB in 30000 iterations
> LVAMP-pwgrid  nl T=4 trainrate=0.01 nmse=-13.019216 dB in 28000 iterations
> LVAMP-pwgrid  nl T=5 trainrate=0.01 nmse=-13.316851 dB in 22000 iterations
> LVAMP-pwgrid  nl T=6 trainrate=0.01 nmse=-13.418649 dB in 31000 iterations

@fahimehansari , Have you been able to get your simulations to behave better?

**Comment by mborgerding** [comment]
bump....

**Comment by fahimehansari** [comment]
Dear Mark, Very thanks for your answering. as you had guessed, in my code maxit was too low. I set maxit=1000000 and the results for fig12 became true.

**Comment by mborgerding** [comment]
Great!  Thanks for the update.  It was a fruitful discussion as it turned up the gradient underflow problem.
Best of luck!
